on: ["push", "pull_request"]

name: Test Codecov

jobs:

  test-coverage:
    name: Generate coverage report
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Use pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: pnpm install, generate coverage report
      run: |
        pnpm i
        pnpm run test-cov

    - name: Send coverage report to codecov for visualization
      uses: codecov/codecov-action@v3
      with:
        verbose: true
